### ISSUE TITLE
setup.py refers to README

### ISSUE THREAD

**Issue by jorjun** [xav/Grapefruit#8]
Must refer to README.rst or build fail error

**Comment by deronsizemore** [comment]
I'm getting something similar:

Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    Main()
  File "setup.py", line 63, in Main
    METADATA['long_description'] = BuildLongDescription()
  File "setup.py", line 59, in BuildLongDescription
    return '\n'.join([Read('README'), Read('CHANGES')])
  File "setup.py", line 56, in Read
    return open(file).read()
IOError: [Errno 2] No such file or directory: 'README'

Would love if someone has a fix for this. Would really like to use grapefruit but if setup.py won't install, I'm not sure how else to use it?

**Comment by jorjun** [comment]
I changed setup.py to refer to README.rst instead of just README, install went OK after.

**Comment by deronsizemore** [comment]
Thanks. That worked.
